name: release

on: [ push ]

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Gradle build
        run: ./gradlew build
      - name: Print directory tree
        run: find .
      - name: Gradle test
        run: ./gradlew test
      - name: Get version string
        run: export VERSION=$(echo ${{ github.ref }} | sed 's/-.\+//')
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: build/libs/kbackup-fabric*
          tag: 1.7.1
          release_name: ${{ env.VERSION }}
          prerelease: true